### PR TITLE
Update route.js

### PR DESCRIPTION
**Pull request by MFBrewster**
`this.get('auth')` not defined in solution branch

### CODE REVIEW

**Comment by jrhorn424** [comment]
Please add any other changes you made and then I'll test and merge. Thanks! (See #6)

**Comment by faetea** [comment]
I submitted a pull request.  
@jrhorn424  There are two changes that are necessary for SignOut to work.
@MFBrewster  Please check my request to see if you have included the second change in your project already.

**Comment by MFBrewster** [comment]
I did not already have that in my pull request, although I did have it in my version of the app. Just forgot that the action had to bubble up all the way to the application route.

**Comment by gaand** [comment]
@MFBrewster Thanks Mike!  I merged @faetea's pull request, so I'm closing this one.

I hope you are well.  Come by and say hi if you get a chance.

**Pull request closed without merging**
